Brixel/HaSpMan

Commands/AddMemberCommand.cs, Commands/EditMemberCommand.cs, Persistence/EntityConfigurations/MemberConfiguration.cs, Persistence/Migrations/20210921181139_IncreaseAddressHouseNumberLength.Designer.cs, Persistence/Migrations/20210921181139_IncreaseAddressHouseNumberLength.cs, Web/Models/MemberForm.cs
=> feat: Increase house number length to 15

Web/Pages/Members/Members.razor
Delete tooltip is renamed to edit
=> #13 Rename delete to edit

Commands/AddMemberCommand.cs, Commands/EditMemberCommand.cs, Web/Models/MemberForm.cs, Web/Pages/Members/MemberForm.razor
=> fix: Correctly validate membership fee when editing/adding members

Commands/AddBankAccountCommand.cs, Commands/Handlers/AddBankAccountHandler.cs, Domain/BankAccount.cs, Domain/Interfaces/IBankAccountRepository.cs, Persistence/EntityConfigurations/BankAccountConfiguration.cs, Persistence/HaSpManContext.cs, Persistence/Migrations/20211001194958_AddBankAccounts.Designer.cs, Persistence/Migrations/20211001194958_AddBankAccounts.cs, Persistence/Repositories/BankAccountRepository.cs, Queries/BankAccounts/GetBankAccounts.cs, Queries/BankAccounts/Handlers/GetBankAccountsHandler.cs, Queries/BankAccounts/ViewModels/BankAccountDetail.cs, Web/Startup.cs
feat: Added BankAccount domain, AddBankAccount command and handler
feat: Added GetBankAccounts query/handler
Partly implements #18 
UI still to be done
=> Add bankaccount domain

Types/TransactionType.cs, Web/Models/TransactionForm.cs, Web/Pages/Transactions/EditTransaction.razor, Web/Pages/Transactions/TransactionForm.razor, Web/Pages/Transactions/TransactionTypeGroup.cs
Switch the debit and credit representation
=> fix: Switch debit and credit #46

Commands.Test/Commands.Test.csproj, Commands/Commands.csproj, Persistence/Persistence.csproj, Queries.Test/Queries.Test.csproj, Queries/Queries.csproj, Web.Test/Web.Test.csproj, Web/Web.csproj
This PR just updates nuget packages to latest versions.
=> chore: update nuget packages

Web/Pages/Members/NewMember.razor
Set `Belgium` as the default country when adding a new member
=> feat: Set Belgium as default country for new members #26

Web/Pages/Transactions/Transactions.razor
Date time formatting set to `dd-MM-yyyy`
=> feat: set datetime in transactions to dd-MM-yyyy

Web/Extensions/AuthExtensions.cs, Web/Shared/MainLayout.razor
=> fix: Perform logout on keycloak so any sessions are invalidated

Infrastructure/helm-charts/haspman/templates/NOTES.txt
This change ensures that some useful information is shown after deploying or upgrading the helm chart
=> ci: Add some useful information to the helm chart notes

Web/Pages/Transactions/TransactionForm.razor
Fixed date format on transaction form
=> fix: make transaction form date freely editable

Commands/Handlers/Member/AddMember/AddMemberCommand.cs, Commands/Handlers/Member/EditMember/EditMemberCommand.cs, Domain/Member.cs, Persistence/Migrations/20220909211334_MakeMemberEmailAndPhoneNullable.Designer.cs, Persistence/Migrations/20220909211334_MakeMemberEmailAndPhoneNullable.cs, Queries/Members/Handlers/SearchMembers/SearchMembersHandler.cs, Web/Models/MemberForm.cs, Web/Pages/Members/MemberForm.razor, Web/Validators/RequiredIfStringEqualsAttribute.cs
=> fix: Change validation to require either email or phone number, not both

Domain/Member.cs, Queries/MapperProfiles/MemberProfile.cs, Queries/Members/ViewModels/MemberSummary.cs
This PR is to open the discussion on how and when a member is active.
=> feat: calculate the member's active state

Web/App.razor, Web/Pages/Public/LoginButton.razor
Instead of automatically being redirected to the configured identity provider, this PR adds a login button to the application
=> #88 Adds login button instead of redirect to keycloak

Commands/Handlers/Member/ExtendMembership/ExtendMembershipCommand.cs, Web/Pages/Transactions/TransactionForm.razor
An expiry date can be set in the past
=> fix: expiry date can be set in the past #54

Web/Pages/Transactions/TransactionForm.razor
Don't set the fixed date of the expiration date.
=> fix: Don't set fixed date

Web/Pages/Members/NewMember.razor
=> fix: Fix mapping issue when creating new member

Queries/Members/Handlers/SearchMembers/SearchMembersHandler.cs, Queries/Members/Handlers/SearchMembers/SearchMembersQuery.cs, Web/Pages/Members/Members.razor
=> feat: Show membership expiry date on members list

Persistence/Migrations/20230728184205_TransactionsBelongToFinancialYear.cs
Adds UPDATE statement for transactions
=> fix: update existing transactions

Persistence/Migrations/20230908191221_FixCreditTransactionAmountOnTotalsView.Designer.cs, Persistence/Migrations/20230908191221_FixCreditTransactionAmountOnTotalsView.cs, Web/Pages/FinancialYears/FinancialYears.razor
=> fix: Update BankAccountTotals view with correct negative modifier for CreditTransactions

Persistence/Repositories/FinancialYearRepository.cs, Web/Pages/Transactions/NewTransaction.razor, Web/Pages/Transactions/TransactionForm.razor
=> Transaction fixes

Domain/Member.cs, Queries/Members/Handlers/SearchMembers/SearchMembersHandler.cs
=> fix: Use static Expression instead of function which can't be translated to SQL

Commands/Handlers/FinancialYear/CloseFinancialYear/CloseFinancialYearHandler.cs, Commands/Handlers/Transaction/AddCreditTransaction/AddCreditTransactionHandler.cs, Queries/FinancialYears/GetFinancialYearsQuery.cs, Web/Pages/FinancialYears/FinancialYears.razor, Web/Program.cs
=> fix: Disable button to close financial year if it is already closed

Commands/Handlers/Transaction/AddCreditTransaction/AddCreditTransactionHandler.cs, Commands/Handlers/Transaction/AddDebitTransaction/AddDebitTransactionHandler.cs, Commands/Handlers/Transaction/EditTransaction/EditTransactionHandler.cs, Web/Pages/FinancialYears/FinancialYears.razor
- fix: Fix financial year handling when adding/editing transactinos
- Throw exception when financial year isn't found instead of creating new one
- Use correct method to get financial year by transaction id
- feat: Add button to create new financial year
=> Fix transactions and financial years
